name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: npm install and build
      run: |
        npm install
        npm run build --if-present
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sftp://skymaster.dreamhost.com:22/home/stefanoperfili/public/today-test/
        ftp-username: stefanoperfili
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: build/
        git-ftp-args: --insecure
